# define Project Root relative to Makefile location
PROJ_ROOT := $(abspath ../..)

TARGET    := test.out
SOURCES   := test_runner.c $(PROJ_ROOT)/shared/utils.c my_memcpy.c

include $(PROJ_ROOT)/shared/common.mk